version: '3.8'

services:
  php:
    image: yiisoftware/yii2-php:8.1-apache
    volumes:
      - ./:/app:delegated
    ports:
      - "8888:80"
  db:
    image: mysql:8.0
    container_name: tasks
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: taskdb

  phpmyadmin:
    image: phpmyadmin
    restart: always
    ports:
      - '3640:80'
    depends_on:
      - db
  composer:
    image: composer/composer
    command: install
    volumes:
      - ./:/var/www/html



